---

# Join domain
- name: Configure DNS settings
  win_dns_client:
      adapter_names: Ethernet
      ipv4_addresses:
      - 10.13.37.10
      - 8.8.8.8

- name: Join machine to domain
  win_domain_membership:
    dns_domain_name: "{{ domain_name }}"
    hostname: "winserv2019"
    domain_admin_user: "{{ ansible_user }}@{{ domain_name }}"
    domain_admin_password: "{{ ansible_password }}"
    state: domain
  register: domain_state

- name: Reboot after joining domain
  win_reboot:
  when: domain_state.reboot_required

# Install vulnerable IIS web server
- name: Install IIS Web-Server with sub features and management tools
  win_feature:
    name: Web-Server
    state: present
    include_sub_features: yes
    include_management_tools: yes
  register: win_feature

- name: Copy webserver files
  win_copy:
    src: files/webserver/
    dest: C:\inetpub\wwwroot

- name: Remove default webserver files
  win_file:
    path: "{{ item }}"
    state: absent
  loop:
    - C:\inetpub\wwwroot\iisstart.html
    - C:\inetpub\wwwroot\iisstart.png

- name: Give IIS_IUSRS control of webserver files
  win_acl:
    path: C:\inetpub\wwwroot
    user: IIS_IUSRS
    rights: FullControl
    type: allow
    state: present
    inherit: ContainerInherit, ObjectInherit
    propagation: 'None'

- name: Reboot if installing Web-Server feature requires it
  win_reboot:
  when: win_feature.reboot_required