---
windows:
  children:
    dc:
      hosts:
        10.13.37.10:
    winserv2019:
      hosts:
        10.13.37.100:
    win10:
      hosts:
        10.13.37.150:

linux:
  children:
    elastic-server:
      hosts:
        10.13.37.50:

elastic:
  children:
    windows:
    elastic-server: